[package]
name = "rust-trace-event-profiler"
version = "0.1.0"
authors = ["Yuya Taniguchi"]
edition = "2018"

[dependencies]
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
derive_builder = "0.9.0"
